project:
  type: website
  output-dir: docs

website:
  image: "https://quarto.org/quarto-dark-bg.jpeg"
  announcement: 
    content: "**WIP** - this website is in progress, official release 12/03/2026" 
    position: below-navbar 
    type: warning
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
  favicon: SCC-HexSticker.png
  open-graph: true
  navbar:
    logo: man\figures\ssc-flatly-banner.png
    background: primary
    search: true
    left:
      - text: "Book"
        href: index.qmd
      - text: "Interactive"
        href: interactive.qmd
      - text: "More"
        menu:
          - text: "Slides (french)"
            href: presentation/presentation-fr.qmd
            target: _blank
          - text: "About Exact test"
            href: bin2arms-exact.qmd
          - text: "Lakatos & Lan"
            href: lakatos_n_lan.qmd
          - text: "Required Events"
            href: surv/survival-event-comparison.qmd
      - text: "Code"
        href: "explain-code/code-home.qmd"
      - text: "About"
        href: about.qmd
    tools:
      - icon: globe
        href: https://oncostat.github.io/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Oncostat/sample-size-comparison
          - text: Report a Bug
            href: https://github.com/Oncostat/sample-size-comparison/issues/new
  sidebar:
    - title : "Book"
      style: "docked"
      contents:
        - text: "Welcome"
          href: index.qmd
        - text: "Introduction"
          href: introduction.qmd
        - section: "Time-to-Event endpoints"
          href: surv/survival-endpoint.qmd
          contents:
            - text: "Method: Sample Size Computation For Survival Endpoints"
              href: surv/survival-methods.qmd
            - text: "Two-arm Fixed Design"
              href: surv/survival-fixed.qmd
            - text: "Two-arm GS-Design"
              href: surv/survival-gs.qmd
            - text: "One-arm Fixed Design"
              href: surv/survival-one-arm.qmd
        - section: "Binary endpoints"
          href: bin/binary-endpoints.qmd
          contents:
            - text: "Method: Binary Tests"
              href: bin/binary-methods.qmd
            - text: "Two-arm Fixed Design"
              href: bin/binary-fixed.qmd
            - text: "Two-arm GS-Design"
              href: bin/binary-gs.qmd
            - text: "One-arm Fixed Design"
              href: bin/binary-one-arm.qmd
        - text: "References"
          href: references.qmd

format:
  html:
    page-navigation: true
    highlight-style: github
    code-fold: show
    execute:
      echo: false
      warning: false
      message: false
    theme:
      light: flatly
      dark: [darkly, custom-dark.scss]
    toc: true
    css: styles.css
fig-format: svg
mermaid-format: svg




