---
title: "Sample Size Comparison"
subtitle: "R as an alternative to East and nQuery ?"
bibliography: references.bibtex
author:
  - name: Arocena Thomas
    orcid: 0009-0002-7014-220X
    email: arocena.thomas@gmail.com
    role: "Stagiaire"
    affiliations: Oncostat
  - name: Dan Chaltiel
    email: dan.chaltiel@gustaveroussy.fr
    orcid: 0000-0003-3488-779X
    role: "Encadrant"
  - name: Anne Lourdessamy
    email: anne.lourdessamy@gustaveroussy.fr
    orcid: 0009-0006-9051-3302
    role: "Encadrante"
date: last-modified
other-links:
  - text: Presentation (in french)
    href: https://oncostat.github.io/sample-size-comparison/presentation/presentation-fr
    icon: file-slides-fill
listing:
  id: sample-listings
  type: grid
  contents:
    - "bin2arms-exact.qmd"
    - "presentation/presentation-fr.qmd"
    - "lakatos_n_lan.qmd"
---

::: {.callout-caution}
## Work In Progress

The website is in construction, It will be completed in the next weeks so be patient ;)
:::

Welcome to this project dedicated to a focused comparison of computed sample sizes produced by East, nQuery, and R packages. This work looks specifically at the numerical results generated by each tool, placing them side by side to examine their consistency, differences, and overall behavior. Rather than exploring technical details on this page, the goal here is to offer a clear entry point into a structured comparison based purely on output values. I invite you to explore the results and discover how these tools align — or differ — when it comes to calculating sample size.


## Motivations
### Why R for sample size calculation ?

- Do all analysis in R without having to use an external tool
- Share code to someone (better than share an East of nQuery project)
- Avoid problem with export
- Free and open-source code, allows to open issue, ask new feature, fork the code

## Scope of the comparison 

| Endpoints  | Design Type              | Computation | Software           | R package                        |
|:-----------|:-------------------------|------------:|:-------------------|:---------------------------------|
| Binary     | Two-arm Fixed            | Pooled      | 🟧East, 🟦nQuery  | 🟥Rpact, ~~🟨bbssr~~            |
| Binary     | Two-arm Fixed            | Unpooled    | 🟧East, 🟦nQuery  | -                                |
| Binary     | Two-arm Fixed            | Exact       | 🟧East, 🟦nQuery  | 🟨bbssr                         |
| Binary     | Two-arm Group-Sequential | Pooled      | 🟧East            | 🟥Rpact                          |
| Binary     | One-arm Fixed            | Exact       | 🟧East            | A'Hern(no package)               |
| Binary     | One-arm Fixed            | Non_exact?  | 🟧East, 🟦nQuery  | 🟥Rpact                         |
| Survival   | Two-arm Fixed            |             | 🟧East, 🟦nQuery  | 🟥Rpact, 🟪Rashnu, 🟫gsDesign2 |
| Survival   | Two-arm Group-Sequential |             | 🟧East, 🟦nQuery  | 🟥Rpact, 🟫gsDesign2            |
| Survival   | One-arm Fixed            |             | 🟧East, 🟦nQuery  | oa2s^[OneArm2stage], sssas^[SampleSizeSingleArmSurvival], 🟪Rashnu|

## Additional content:

::: {#sample-listings}
:::

