---
title: Comparaison East/Rpact
subtitle: Différence de résultats entre les event sizes et samples sizes obtenuent pour des essais cliniques à 2 bras.
author:
  - name: AROCENA Thomas 
    orcid: 0009-0002-7014-220X
abstract: |
  {{< lipsum 1 >}}
papersize: a4
format: 
  typst
keywords:
  - Quarto
  - Typst
  - format
date: today
date-format: full
logo:
  width: 1in
  padding: 0.375in
  location: left-top
brand: brand\_brand.yml
execute:
  echo: true
margin: 
  x: 1.25in
  y: 1.25in
lang: "fr"
---

```{r}
#| label: package_setup
#| echo: false
#| message: false
#| warning: false
library(gt)
library(rpact)
library(tidyverse)
```

```{r}
#| label: grid_search_params
#| echo: false
alpha = c(0.01, 0.05, 0.1, 0.20, 0.5)
power = c(0.5, 0.8, 0.9, 0.99, NA)
hr = c(0.1, 0.5, 0.7, 0.9, 0.99)
surv_3y = c(0.1, 0.3, 0.6, 0.9, NA)

tibble(
  alpha = alpha,
  power = power,
  hr = hr,
  surv_3y = surv_3y
) |>
  gt() |>
  sub_missing()
```

::: {.block fill="luma(200)" inset="8pt" radius="4pt"}

This is a block with gray background and slightly rounded corners.

:::



```{r}
#| label: rpact_getEventsFixed
sample_size_info <- getSampleSizeSurvival(
  alpha = 0.05,
  sided = 2,
  beta = 0.1,
  typeOfComputation = "Schoenfeld",
  hazardRatio = 0.7,
  pi2 = 0.3,
  eventTime = 3,
  followUpTime = 3,
  accrualTime = c(0, 3)
)

sample_size_info$eventsFixed
sample_size_info$nFixed
```

```{r}
#| label: get_sample_size_wrapper
get_sample_size_wrapper <- function(
  alpha,
  power,
  hr,
  surv_3y,
  error = NA_real_
  ){
  tryCatch({
  # Times are in year NOT months
  sample_size_info <- getSampleSizeSurvival(
    alpha = alpha,
    beta = 1 - power,
    hazardRatio = hr,
    pi2 = surv_3y,
    eventTime = 3, # 3 years survival
    typeOfComputation = "Schoenfeld",
    sided = 2,
    allocationRatioPlanned = 1,
    dropoutRate1 = 0,
    dropoutRate2 = 0,
    followUpTime = 3, # 3 years of follow-up after accrual
    accrualTime = c(0, 3) # 3 years of accrual
  )

  return(tibble(
    e = sample_size_info$eventsFixed,
    n = sample_size_info$nFixed))
  },
  error = function(er){
    return(tibble(e = error, n = error))
  })
}

get_sample_size_wrapper(0.49,0.51,0.1,0.6)
```

```{r}
param_list = list(
  alpha = c(0.01, 0.05, 0.1, 0.20, 0.49),
  power = c(0.51, 0.8, 0.9, 0.99),
  hr = c(0.1, 0.5, 0.7, 0.9, 0.99),
  surv_3y = c(0.1, 0.3, 0.6, 0.9)
)

param_table <- 
  param_list |> 
  expand.grid() |> 
  as_tibble()

p_res <- 
  param_table |> 
  mutate(
    nested_res = pmap(param_table,get_sample_size_wrapper)
    ) |> 
  unnest(nested_res)

head(p_res) |> gt()
write_csv(p_res, "results/rpact_grid.csv")
```