---
title: "Two-arms Fixed Design with Time-to-Event endpoint."
bibliography: references.bibtex
---

```{r}
#| label: initialisation
#| echo: false
#| message: false
#| warning: false
source("R/init.R")
library(plotly)
library(crosstalk)
library(bslib)
library(bsicons)
library(DT)
```

```{r}
#| label: get-ssc-object
#| echo: false
ssc <- read_rds("ssc.rds")
```

```{r}
#| echo: false
surv_fixed <- ssc$surv$fixed$combined |> get_tbl()
shared_surv_fixed <- SharedData$new(surv_fixed)
```


```{r}
#| echo: false
#| warning: false
card(
  height = 300,
  full_screen = TRUE,
  card_header("Survival fixed sample size",
    tooltip(
        bs_icon("info-circle"),
        "East is considered the references"
    )),
  layout_sidebar(
    fillable = TRUE,
    sidebar = sidebar(
      filter_select("relevancy", "Relevancy:", shared_surv_fixed, ~ relevancy)
    ),
    plot_ly(shared_surv_fixed) |> 
        add_trace(
        x = ~ n_east,
        y = ~ n_rpact,
        color = ~ relevancy,
        type = "scatter",
        mode = "markers"
    ), 
    plot_ly(shared_surv_fixed) |> 
        add_trace(
            x = ~ n_east,
            y = ~ n_nquery,
            color = ~ relevancy,
            type = "scatter",
            mode = "markers"
        ),
    datatable(shared_surv_fixed)
  )
)
```

```{r}
#| echo: false
#| warning: false
layout_sidebar(
    fillable = TRUE,
    sidebar = sidebar(
      filter_select("relevancy", "Relevancy:", shared_surv_fixed, ~ relevancy)
    ),
    plot_ly(shared_surv_fixed) |> 
        add_trace(
        x = ~ n_east,
        y = ~ n_rpact,
        color = ~ relevancy,
        type = "scatter",
        mode = "markers"
    ), 
    plot_ly(shared_surv_fixed) |> 
        add_trace(
            x = ~ n_east,
            y = ~ n_nquery,
            color = ~ relevancy,
            type = "scatter",
            mode = "markers"
        ),
    datatable(shared_surv_fixed)
  )
```